version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=127.0.0.1
    volumes:
      - .:/app
    restart: unless-stopped